### ISSUE TITLE
Navbar für Mobile-Menu kaputt

### ISSUE THREAD

**Issue by TeePfote** [TeePfote/Quiz_Website#2]
In der Mobil Ansicht funktioniert das aufklappen der Navbar nicht mehr über die 3 Striche, seid dem letzten oder vorletzten push.

**Comment by Lucadmin** [comment]
Fixed by https://github.com/TeePfote/Quiz_Website/commit/2c0012dd0f0a00cc0700908d21d1a2ce660f6418
